version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    environment:
      - PHP_OPCACHE_ENABLE=0
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    command: php artisan serve --host=0.0.0.0 --port=8000

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    working_dir: /app
    environment:
      - NG_CLI_ANALYTICS=false
      - CHOKIDAR_USEPOLLING=true
    command: npm run start -- --host=0.0.0.0 --poll 1000
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql-app
    ports:
       - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: